'use strict';

systemDictionary = {
  '<em>Hint:</em> Click on the ?-button at the top to get help and some examples.': {
    'en': '<em>Hint:</em> Click on the ?-button at the top to get help and some examples.',
    'de': '<em>Hinweis:</em> Klicke auf den ?-Button weiter oben um Hilfe und einige Beispiele zu erhalten.',
    'ru': '<em>Подсказка:</em> Нажмите на ?-Кнопка вверху, чтобы получить помощь и несколько примеров.',
    'pt': '<em>Dica:</em> Clique no botão? Na parte superior para obter ajuda e alguns exemplos.',
    'nl': '<em>Hint:</em> Klik op de? -Knop bovenaan voor hulp en enkele voorbeelden.',
    'fr': "<em>Astuce:</em> cliquez sur le bouton? En haut pour obtenir de l'aide et des exemples.",
    'it': '<em>Suggerimento:</em> fai clic sul pulsante? In alto per ottenere assistenza e alcuni esempi.',
    'es': '<em>Sugerencia:</em> haga clic en el botón? En la parte superior para obtener ayuda y algunos ejemplos.',
    'pl': '<em>Wskazówka:</em> kliknij przycisk? U góry, aby uzyskać pomoc i kilka przykładów.',
    'zh-cn': '<em>提示：</em>单击顶部的？按钮以获取帮助和一些示例。'
  },
  'Add entry': {
    'en': 'Add entry',
    'de': 'Eintrag hinzufügen',
    'ru': 'Добавить запись',
    'pt': 'Adicionar entrada',
    'nl': 'Vermelding toevoegen',
    'fr': 'Ajouter une entrée',
    'it': 'Aggiungi voce',
    'es': 'Añadir entrada',
    'pl': 'Dodaj wpis',
    'zh-cn': '添加条目'
  },
  'Address': {
    'en': 'Address',
    'de': 'Adresse',
    'ru': 'Адрес',
    'pt': 'Endereço',
    'nl': 'Adres',
    'fr': 'Adresse',
    'it': 'Indirizzo',
    'es': 'Habla a',
    'pl': 'Adres',
    'zh-cn': '地址'
  },
  'Allowed chars: a-z A-Z 0-9 - _ .': {
    'en': 'Allowed chars: a-z A-Z 0-9 - _ .',
    'de': 'Gültige Zeichen: a-z A-Z 0-9 - _ .',
    'ru': 'Разрешенные символы: a-z A-Z 0-9 - _ .',
    'pt': 'Caracteres permitidos: a-z A-Z 0-9 - _ .',
    'nl': 'Toegestane tekens: a-z A-Z 0-9 - _ .',
    'fr': 'Caractères autorisés: a-z A-Z 0-9 - _ .',
    'it': 'Caratteri consentiti: a-z A-Z 0-9 - _ .',
    'es': 'Caracteres permitidos: a-z A-Z 0-9 - _ .',
    'pl': 'Dozwolone znaki: a-z A-Z 0-9 - _ .',
    'zh-cn': '允许的字符：a-z A-Z 0-9 - _ .'
  },
  'Baud rate': {
    'en': 'Baud rate',
    'de': 'Baudrate',
    'ru': 'Скорость передачи',
    'pt': 'Taxa de transmissão',
    'nl': 'Baudsnelheid',
    'fr': 'Débit en bauds',
    'it': 'Baud rate',
    'es': 'Velocidad de transmisión',
    'pl': 'Szybkość transmisji',
    'zh-cn': '波特率'
  },
  'Data': {
    'en': 'Data',
    'de': 'Daten',
    'ru': 'Данные',
    'pt': 'Dados',
    'nl': 'Gegevens',
    'fr': 'Les données',
    'it': 'Dati',
    'es': 'Datos',
    'pl': 'Dane',
    'zh-cn': '数据'
  },
  'Data type': {
    'en': 'Data type',
    'de': 'Datentyp',
    'ru': 'Тип данных',
    'pt': 'Tipo de dados',
    'nl': 'Data type',
    'fr': 'Type de données',
    'it': 'Tipo di dati',
    'es': 'Tipo de datos',
    'pl': 'Typ danych',
    'zh-cn': '数据类型'
  },
  'Decimals': {
    'en': 'Decimals',
    'de': 'Dezimalstellen',
    'ru': 'Десятичные',
    'pt': 'Decimais',
    'nl': 'Decimalen',
    'fr': 'Décimales',
    'it': 'Decimali',
    'es': 'Decimales',
    'pl': 'Liczby dziesiętne',
    'zh-cn': '小数点'
  },
  'Duplicate names are not allowed': {
    'en': 'Duplicate names are not allowed',
    'de': 'Doppelte Namen sind nicht erlaubt',
    'ru': 'Дубликаты имен не допускаются',
    'pt': 'Nomes duplicados não são permitidos',
    'nl': 'Dubbele namen zijn niet toegestaan',
    'fr': 'Les noms en double ne sont pas autorisés',
    'it': 'I nomi duplicati non sono ammessi',
    'es': 'No se permiten nombres duplicados.',
    'pl': 'Zduplikowane nazwy są niedozwolone',
    'zh-cn': '不允许重复的名称'
  },
  'Empty names are not allowed': {
    'en': 'Empty names are not allowed',
    'de': 'Leere Namen sind nicht erlaubt',
    'ru': 'Пустые имена не допускаются',
    'pt': 'Nomes vazios não são permitidos',
    'nl': 'Lege namen zijn niet toegestaan',
    'fr': 'Les noms vides ne sont pas autorisés',
    'it': 'I nomi vuoti non sono ammessi',
    'es': 'No se permiten nombres vacíos.',
    'pl': 'Puste nazwy są niedozwolone',
    'zh-cn': '不允许使用空名称'
  },
  'Empty port is not allowed': {
    'en': 'Empty port is not allowed',
    'de': 'Leere Schnittstelle ist nicht erlaubt',
    'ru': 'Пустой порт не допускается',
    'pt': 'Porta vazia não é permitida',
    'nl': 'Lege poort is niet toegestaan',
    'fr': "Le port vide n'est pas autorisé",
    'it': 'La porta vuota non è consentita',
    'es': 'El puerto vacío no está permitido',
    'pl': 'Pusty port jest niedozwolony',
    'zh-cn': '不允许使用空端口'
  },
  'Error': {
    'en': 'Error',
    'de': 'Fehler',
    'ru': 'ошибка',
    'pt': 'Erro',
    'nl': 'Fout',
    'fr': 'Erreur',
    'it': 'Errore',
    'es': 'Error',
    'pl': 'Błąd',
    'zh-cn': '错误'
  },
  'Factor': {
    'en': 'Factor',
    'de': 'Faktor',
    'ru': 'фактор',
    'pt': 'Fator',
    'nl': 'Factor',
    'fr': 'Facteur',
    'it': 'Fattore',
    'es': 'Factor',
    'pl': 'Czynnik',
    'zh-cn': '因子'
  },
  'From address': {
    'en': 'From address',
    'de': 'Von-Adresse',
    'ru': 'С адреса',
    'pt': 'A partir do endereço',
    'nl': 'Van adres',
    'fr': "De l'adresse",
    'it': "Dall'indirizzo",
    'es': 'De la Dirección',
    'pl': 'Z adresu',
    'zh-cn': '发件人地址'
  },
  'In promiscuous mode, messages addressed to an any node can be received. Remember to set the <code>toAddress</code> for incoming data if enabled.': {
    'en': 'In promiscuous mode, messages addressed to an any node can be received. Remember to set the <code>toAddress</code> for incoming data if enabled.',
    'de': 'Im Promiscuous-Modus können Nachrichten, die an irgendeinen Empfänger addressiert sind, empfangen werden. Beachte die <code>Zu-Adresse</code> für eingehende Daten zu setzen, wenn diese Funktion aktiviert ist.',
    'ru': 'В случайном режиме могут быть получены сообщения, адресованные любому узлу. Не забудьте установить <code>Адресовать</code> для входящих данных, если они включены.',
    'pt': 'No modo promíscuo, as mensagens endereçadas a qualquer nó podem ser recebidas. Lembre-se de definir o <code>toAddress</code> para os dados recebidos, se ativado.',
    'nl': 'In promiscue modus kunnen berichten die zijn geadresseerd aan een willekeurig knooppunt worden ontvangen. Vergeet niet om het <code>toAddress</code> voor inkomende gegevens indien ingeschakeld.',
    'fr': "En mode promiscuous, les messages adressés à n'importe quel nœud peuvent être reçus. N'oubliez pas de définir <code>toAddress</code> pour les données entrantes si elles sont activées.",
    'it': 'In modalità promiscua, è possibile ricevere messaggi indirizzati a qualsiasi nodo. Ricorda di impostare <code>toAddress</code> per i dati in entrata se abilitato.',
    'es': 'En modo promiscuo, se pueden recibir mensajes dirigidos a cualquier nodo. Recuerde configurar <code>toAddress</code> para los datos entrantes si está habilitado.',
    'pl': 'W trybie rozwiązanym można odbierać wiadomości zaadresowane do dowolnego węzła. Pamiętaj, aby ustawić <code>toAddress</code> dla danych przychodzących, jeśli jest włączony.',
    'zh-cn': '在混杂模式下，可以接收发往任何节点的消息。如果启用，请记住为传入数据设置<code>toAddress</code> 。'
  },
  'Incoming data': {
    'en': 'Incoming data',
    'de': 'Eingehende Daten',
    'ru': 'Входящие данные',
    'pt': 'Dados recebidos',
    'nl': 'Inkomende gegevens',
    'fr': 'Données entrantes',
    'it': 'Dati in arrivo',
    'es': 'Datos entrantes',
    'pl': 'Dane przychodzące',
    'zh-cn': '传入数据'
  },
  'Invalid address': {
    'en': 'Invalid address',
    'de': 'Ungültige Adresse',
    'ru': 'Неверный адрес',
    'pt': 'Endereço inválido',
    'nl': 'Ongeldig adres',
    'fr': 'Adresse invalide',
    'it': 'Indirizzo non valido',
    'es': 'Dirección inválida',
    'pl': 'Błędny adres',
    'zh-cn': '无效地址'
  },
  'Invalid data': {
    'en': 'Invalid data',
    'de': 'Ungültige Daten',
    'ru': 'Неверные данные',
    'pt': 'Dados inválidos',
    'nl': 'Onjuiste data',
    'fr': 'Données invalides',
    'it': 'Dati non validi',
    'es': 'Datos inválidos',
    'pl': 'Nieprawidłowe dane',
    'zh-cn': '无效数据'
  },
  'Log all data': {
    'en': 'Log all data',
    'de': 'Alle Daten loggen',
    'ru': 'Записать все данные',
    'pt': 'Registrar todos os dados',
    'nl': 'Log alle gegevens',
    'fr': 'Enregistrer toutes les données',
    'it': 'Registra tutti i dati',
    'es': 'Registrar todos los datos',
    'pl': 'Zaloguj wszystkie dane',
    'zh-cn': '记录所有数据'
  },
  'Name': {
    'en': 'Name',
    'de': 'Name',
    'ru': 'название',
    'pt': 'Nome',
    'nl': 'Naam',
    'fr': 'Nom',
    'it': 'Nome',
    'es': 'Nombre',
    'pl': 'Imię',
    'zh-cn': '名称'
  },
  'Number of retries for each message to be sent. Default is 3. Set to 0 for no retries.': {
    'en': 'Number of retries for each message to be sent. Default is 3. Set to 0 for no retries.',
    'de': 'Anzahl an wiederholten Sendeversuchen für jede zu sendende Nachricht. Standard ist 3. Auf 0 setzen für keine Wiederholung.',
    'ru': 'Количество попыток для каждого сообщения, которое будет отправлено. По умолчанию 3. Установите 0, чтобы не повторять попытки.',
    'pt': 'Número de tentativas para cada mensagem a ser enviada. O padrão é 3. Configure como 0 para nenhuma nova tentativa.',
    'nl': 'Aantal pogingen voor elk te verzenden bericht. De standaardwaarde is 3. Stel in op 0 voor geen nieuwe pogingen.',
    'fr': 'Nombre de tentatives pour chaque message à envoyer. La valeur par défaut est 3. Définissez sur 0 pour aucune nouvelle tentative.',
    'it': "Numero di tentativi per ciascun messaggio da inviare. L'impostazione predefinita è 3. Impostare su 0 per nessun tentativo.",
    'es': 'Número de reintentos para cada mensaje a enviar. El valor predeterminado es 3. Se establece en 0 para que no se vuelvan a intentar.',
    'pl': 'Liczba ponownych prób wysłania każdej wiadomości. Domyślnie jest to 3. Ustaw na 0, aby nie próbować.',
    'zh-cn': '每条要发送消息的重试次数。默认值为3。不重试设置为0。'
  },
  'Offset': {
    'en': 'Offset',
    'de': 'Offset',
    'ru': 'офсет',
    'pt': 'Deslocamento',
    'nl': 'Offset',
    'fr': 'Décalage',
    'it': 'Compensare',
    'es': 'Compensar',
    'pl': 'Offsetowy',
    'zh-cn': '偏移量'
  },
  'Outgoing data': {
    'en': 'Outgoing data',
    'de': 'Ausgehende Daten',
    'ru': 'Исходящие данные',
    'pt': 'Dados enviados',
    'nl': 'Uitgaande gegevens',
    'fr': 'Données sortantes',
    'it': 'Dati in uscita',
    'es': 'Datos salientes',
    'pl': 'Dane wychodzące',
    'zh-cn': '外发数据'
  },
  'Promiscuous mode': {
    'en': 'Promiscuous mode',
    'de': 'Promiscuous-Modus',
    'ru': 'Неразборчивый режим',
    'pt': 'Modo promíscuo',
    'nl': 'Promiscuous mode',
    'fr': 'Mode promiscuité',
    'it': 'Modalità promiscua',
    'es': 'Modo promiscuo',
    'pl': 'Tryb rozwiązły',
    'zh-cn': '混杂模式'
  },
  'Reliable mode': {
    'en': 'Reliable mode',
    'de': 'Zuverlässiger Modus',
    'ru': 'Надежный режим',
    'pt': 'Modo confiável',
    'nl': 'Betrouwbare modus',
    'fr': 'Mode fiable',
    'it': 'Modalità affidabile',
    'es': 'Modo confiable',
    'pl': 'Tryb niezawodny',
    'zh-cn': '可靠模式'
  },
  'Retries': {
    'en': 'Retries',
    'de': 'Wiederholungen',
    'ru': 'Повторы',
    'pt': 'Tentativas',
    'nl': 'Nieuwe pogingen',
    'fr': 'Réessais',
    'it': 'tentativi',
    'es': 'Reintentos',
    'pl': 'Ponawia próbę',
    'zh-cn': '重试'
  },
  'Role': {
    'en': 'Role',
    'de': 'Rolle',
    'ru': 'Роль',
    'pt': 'Função',
    'nl': 'Rol',
    'fr': 'Rôle',
    'it': 'Ruolo',
    'es': 'Papel',
    'pl': 'Rola',
    'zh-cn': '角色'
  },
  'Serial port': {
    'en': 'Serial port',
    'de': 'Serielle Schnittstelle',
    'ru': 'Последовательный порт',
    'pt': 'Porta serial',
    'nl': 'Seriële poort',
    'fr': 'Port série',
    'it': 'Porta seriale',
    'es': 'Puerto serial',
    'pl': 'Port szeregowy',
    'zh-cn': '串行端口'
  },
  'Something seems to be wrong. Please check the highlighted fields.': {
    'en': 'Something seems to be wrong. Please check the highlighted fields.',
    'de': 'Etwas scheint nicht zu stimmen. Bitte prüfe die markierten Felder.',
    'ru': 'Кажется, что-то не так. Пожалуйста, проверьте выделенные поля.',
    'pt': 'Algo parece estar errado. Por favor, verifique os campos destacados.',
    'nl': 'Er lijkt iets mis te zijn. Controleer de gemarkeerde velden.',
    'fr': 'Quelque chose semble mal. Veuillez vérifier les champs en surbrillance.',
    'it': 'Qualcosa sembra essere sbagliato. Si prega di controllare i campi evidenziati.',
    'es': 'Algo parece estar mal. Por favor verifique los campos resaltados.',
    'pl': 'Coś wydaje się nie tak. Sprawdź podświetlone pola.',
    'zh-cn': '似乎有问题。请检查突出显示的字段。'
  },
  'Starting or ending with a dot is not allowed': {
    'en': 'Starting or ending with a dot is not allowed',
    'de': 'Ein Punkt am Anfang oder Ende ist nicht zulässig',
    'ru': 'Начинать или заканчивать точкой запрещено',
    'pt': 'Não é permitido iniciar ou terminar com um ponto',
    'nl': 'Beginnen of eindigen met een punt is niet toegestaan',
    'fr': "Commencer ou terminer par un point n'est pas autorisé",
    'it': "L'inizio o la fine con un punto non sono consentiti",
    'es': 'Comenzar o terminar con un punto no está permitido',
    'pl': 'Rozpoczynanie lub kończenie kropką jest niedozwolone',
    'zh-cn': '不允许以点开头或结尾'
  },
  'The address of this node in the RadioHead network. May be given as hex number (0x00 to 0xFE) or decimal number (0 to 254).': {
    'en': 'The address of this node in the RadioHead network. May be given as hex number (0x00 to 0xFE) or decimal number (0 to 254).',
    'de': 'Die Adresses dieses Knotens im RadioHead-Netzwerk. Kann als Hexadezimalzahl (0x00 bis 0xFE) oder Dezimalzahl (0 bis 254) angegeben werden.',
    'ru': 'Адрес этого узла в сети RadioHead. Может быть дано как шестнадцатеричное число (от 0x00 до 0xFE) или десятичное число (от 0 до 254).',
    'pt': 'O endereço desse nó na rede RadioHead. Pode ser fornecido como número hexadecimal (0x00 a 0xFE) ou número decimal (0 a 254).',
    'nl': 'Het adres van dit knooppunt in het RadioHead-netwerk. Kan worden gegeven als hexadecimaal getal (0x00 tot 0xFE) of decimaal getal (0 tot 254).',
    'fr': "L'adresse de ce nœud dans le réseau RadioHead. Peut être donné sous forme de nombre hexadécimal (0x00 à 0xFE) ou de nombre décimal (0 à 254).",
    'it': "L'indirizzo di questo nodo nella rete RadioHead. Può essere indicato come numero esadecimale (da 0x00 a 0xFE) o numero decimale (da 0 a 254).",
    'es': 'La dirección de este nodo en la red RadioHead. Se puede dar como número hexadecimal (0x00 a 0xFE) o número decimal (0 a 254).',
    'pl': 'Adres tego węzła w sieci RadioHead. Może być podany jako liczba szesnastkowa (0x00 do 0xFE) lub liczba dziesiętna (0 do 254).',
    'zh-cn': '该节点在RadioHead网络中的地址。可以十六进制数（0x00到0xFE）或十进制数（0到254）给出。'
  },
  'Timeout': {
    'en': 'Timeout',
    'de': 'Zeitüberschreitung',
    'ru': 'Тайм-аут',
    'pt': 'Tempo esgotado',
    'nl': 'Time-out',
    'fr': 'Temps libre',
    'it': 'Tempo scaduto',
    'es': 'Se acabó el tiempo',
    'pl': 'Koniec czasu',
    'zh-cn': '超时'
  },
  'Timeout while waiting for an ack for each sent message. Default is 200.': {
    'en': 'Timeout while waiting for an ack for each sent message. Default is 200.',
    'de': 'Zeit in Millisekunden die beim Senden einer Nachricht auf die Bestätigung (ACK) gewartet wird. Standard ist 200.',
    'ru': 'Тайм-аут в ожидании подтверждения для каждого отправленного сообщения. По умолчанию 200.',
    'pt': 'Tempo limite enquanto aguarda uma confirmação para cada mensagem enviada. O padrão é 200.',
    'nl': 'Time-out tijdens het wachten op een antwoord voor elk verzonden bericht. Standaard is 200.',
    'fr': "Délai d'attente en attendant un accusé de réception pour chaque message envoyé. La valeur par défaut est 200.",
    'it': "Timeout durante l'attesa di una conferma per ciascun messaggio inviato. L'impostazione predefinita è 200.",
    'es': 'Tiempo de espera mientras espera un reconocimiento por cada mensaje enviado. El valor predeterminado es 200.',
    'pl': 'Limit czasu oczekiwania na potwierdzenie dla każdej wysłanej wiadomości. Domyślnie jest to 200.',
    'zh-cn': '等待每个已发送消息的确认时超时。默认值为200。'
  },
  'To address': {
    'en': 'To address',
    'de': 'Zu-Adresse',
    'ru': 'Адресовать',
    'pt': 'Endereçar',
    'nl': 'Om aan te pakken',
    'fr': 'Adresser',
    'it': 'Indirizzare',
    'es': 'Dirigirse',
    'pl': 'Adresować',
    'zh-cn': '讲话'
  },
  'Type': {
    'en': 'Type',
    'de': 'Typ',
    'ru': 'Тип',
    'pt': 'Tipo',
    'nl': 'Type',
    'fr': 'Type',
    'it': 'genere',
    'es': 'Tipo',
    'pl': 'Rodzaj',
    'zh-cn': '类型'
  },
  'Unit': {
    'en': 'Unit',
    'de': 'Einheit',
    'ru': 'Единица измерения',
    'pt': 'Unidade',
    'nl': 'Eenheid',
    'fr': 'Unité',
    'it': 'Unità',
    'es': 'Unidad',
    'pl': 'Jednostka',
    'zh-cn': '单元'
  },
  'Use <code>RHReliableDatagram</code> instead of <code>RHDatagram</code>.': {
    'en': 'Use <code>RHReliableDatagram</code> instead of <code>RHDatagram</code>.',
    'de': 'Verwende <code>RHReliableDatagram</code> anstelle von <code>RHDatagram</code>.',
    'ru': 'Используйте <code>RHReliableDatagram</code> вместо <code>RHDatagram</code>.',
    'pt': 'Use <code>RHReliableDatagram</code> vez de <code>RHDatagram</code> .',
    'nl': 'Gebruik <code>RHReliableDatagram</code> plaats van <code>RHDatagram</code> .',
    'fr': 'Utilisez <code>RHReliableDatagram</code> au lieu de <code>RHDatagram</code> .',
    'it': 'Usa <code>RHReliableDatagram</code> invece di <code>RHDatagram</code> .',
    'es': 'Utilice <code>RHReliableDatagram</code> lugar de <code>RHDatagram</code> .',
    'pl': 'Użyj <code>RHReliableDatagram</code> zamiast <code>RHDatagram</code> .',
    'zh-cn': '使用<code>RHReliableDatagram</code>代替<code>RHDatagram</code> 。'
  },
  'When enabled, every received and sent message will be logged.': {
    'en': 'When enabled, every received and sent message will be logged.',
    'de': 'Wenn aktiviert, dann wird jede empfangene und jede gesendete Nachricht in das Log geschrieben.',
    'ru': 'Когда включено, каждое полученное и отправленное сообщение будет зарегистрировано.',
    'pt': 'Quando ativada, todas as mensagens recebidas e enviadas serão registradas.',
    'nl': 'Indien ingeschakeld, wordt elk ontvangen en verzonden bericht vastgelegd.',
    'fr': "Lorsqu'il est activé, chaque message reçu et envoyé sera enregistré.",
    'it': 'Se abilitato, tutti i messaggi ricevuti e inviati verranno registrati.',
    'es': 'Cuando está habilitado, se registrarán todos los mensajes recibidos y enviados.',
    'pl': 'Po włączeniu każda odebrana i wysłana wiadomość będzie rejestrowana.',
    'zh-cn': '启用后，将记录每条接收和发送的消息。'
  },
  'blinds': {
    'en': 'blinds',
    'de': 'Rolladen',
    'ru': 'жалюзи',
    'pt': 'persianas',
    'nl': 'jaloezieën',
    'fr': 'stores',
    'it': 'persiane',
    'es': 'persianas',
    'pl': 'Żaluzje',
    'zh-cn': '百叶窗'
  },
  'boolean': {
    'en': 'boolean',
    'de': 'Wahrheitswert',
    'ru': 'логический',
    'pt': 'boleano',
    'nl': 'boolean',
    'fr': 'booléen',
    'it': 'booleano',
    'es': 'booleano',
    'pl': 'boolean',
    'zh-cn': '布尔值'
  },
  'button': {
    'en': 'button',
    'de': 'Taster',
    'ru': 'кнопка',
    'pt': 'botão',
    'nl': 'knop',
    'fr': 'bouton',
    'it': 'pulsante',
    'es': 'botón',
    'pl': 'przycisk',
    'zh-cn': '纽扣'
  },
  'custom': {
    'en': 'custom',
    'de': 'Benutzerdefiniert',
    'ru': 'обычай',
    'pt': 'personalizadas',
    'nl': 'Op maat',
    'fr': 'Douane',
    'it': 'costume',
    'es': 'personalizado',
    'pl': 'zwyczaj',
    'zh-cn': '习俗'
  },
  'default': {
    'en': 'default',
    'de': 'Standard',
    'ru': 'дефолт',
    'pt': 'padrão',
    'nl': 'standaard',
    'fr': 'défaut',
    'it': 'predefinito',
    'es': 'defecto',
    'pl': 'domyślna',
    'zh-cn': '默认'
  },
  'double64_be': {
    'en': 'double64_be',
    'de': 'double64_be',
    'ru': 'double64_be',
    'pt': 'double64_be',
    'nl': 'double64_be',
    'fr': 'double64_be',
    'it': 'double64_be',
    'es': 'double64_be',
    'pl': 'double64_be',
    'zh-cn': 'double64_be'
  },
  'double64_le': {
    'en': 'double64_le',
    'de': 'double64_le',
    'ru': 'double64_le',
    'pt': 'double64_le',
    'nl': 'double64_le',
    'fr': 'double64_le',
    'it': 'double64_le',
    'es': 'double64_le',
    'pl': 'double64_le',
    'zh-cn': 'double64_le'
  },
  'e.g.': {
    'en': 'e.g.',
    'de': 'z.B.',
    'ru': 'например',
    'pt': 'por exemplo.',
    'nl': 'b.v.',
    'fr': 'par exemple.',
    'it': 'per esempio.',
    'es': 'p.ej.',
    'pl': 'na przykład',
    'zh-cn': '例如'
  },
  'float32_be': {
    'en': 'float32_be',
    'de': 'float32_be',
    'ru': 'float32_be',
    'pt': 'float32_be',
    'nl': 'float32_be',
    'fr': 'float32_be',
    'it': 'float32_be',
    'es': 'float32_be',
    'pl': 'float32_be',
    'zh-cn': 'float32_be'
  },
  'float32_le': {
    'en': 'float32_le',
    'de': 'float32_le',
    'ru': 'float32_le',
    'pt': 'float32_le',
    'nl': 'float32_le',
    'fr': 'float32_le',
    'it': 'float32_le',
    'es': 'float32_le',
    'pl': 'float32_le',
    'zh-cn': 'float32_le'
  },
  'indicator': {
    'en': 'indicator',
    'de': 'Indikator',
    'ru': 'показатель',
    'pt': 'indicador',
    'nl': 'indicator',
    'fr': 'indicateur',
    'it': 'indicatore',
    'es': 'indicador',
    'pl': 'wskaźnik',
    'zh-cn': '指示符'
  },
  'int16_be': {
    'en': 'int16_be',
    'de': 'int16_be',
    'ru': 'int16_be',
    'pt': 'int16_be',
    'nl': 'int16_be',
    'fr': 'int16_be',
    'it': 'int16_be',
    'es': 'int16_be',
    'pl': 'int16_be',
    'zh-cn': 'int16_be'
  },
  'int16_le': {
    'en': 'int16_le',
    'de': 'int16_le',
    'ru': 'int16_le',
    'pt': 'int16_le',
    'nl': 'int16_le',
    'fr': 'int16_le',
    'it': 'int16_le',
    'es': 'int16_le',
    'pl': 'int16_le',
    'zh-cn': 'int16_le'
  },
  'int32_be': {
    'en': 'int32_be',
    'de': 'int32_be',
    'ru': 'int32_be',
    'pt': 'int32_be',
    'nl': 'int32_be',
    'fr': 'int32_be',
    'it': 'int32_be',
    'es': 'int32_be',
    'pl': 'int32_be',
    'zh-cn': 'int32_be'
  },
  'int32_le': {
    'en': 'int32_le',
    'de': 'int32_le',
    'ru': 'int32_le',
    'pt': 'int32_le',
    'nl': 'int32_le',
    'fr': 'int32_le',
    'it': 'int32_le',
    'es': 'int32_le',
    'pl': 'int32_le',
    'zh-cn': 'int32_le'
  },
  'int8': {
    'en': 'int8',
    'de': 'int8',
    'ru': 'int8',
    'pt': 'int8',
    'nl': 'int8',
    'fr': 'int8',
    'it': 'int8',
    'es': 'int8',
    'pl': 'int8',
    'zh-cn': 'int8'
  },
  'number': {
    'en': 'number',
    'de': 'Zahl',
    'ru': 'число',
    'pt': 'número',
    'nl': 'aantal',
    'fr': 'nombre',
    'it': 'numero',
    'es': 'número',
    'pl': 'numer',
    'zh-cn': '数'
  },
  'switch': {
    'en': 'switch',
    'de': 'Schalter',
    'ru': 'переключатель',
    'pt': 'interruptor',
    'nl': 'schakelaar',
    'fr': 'commutateur',
    'it': 'interruttore',
    'es': 'cambiar',
    'pl': 'przełącznik',
    'zh-cn': '开关'
  },
  'temperature': {
    'en': 'temperature',
    'de': 'Temperatur',
    'ru': 'темпаратура',
    'pt': 'temperatura',
    'nl': 'temperatuur',
    'fr': 'Température',
    'it': 'temperatura',
    'es': 'temperatura',
    'pl': 'temperatura',
    'zh-cn': '温度'
  },
  'uint16_be': {
    'en': 'uint16_be',
    'de': 'uint16_be',
    'ru': 'uint16_be',
    'pt': 'uint16_be',
    'nl': 'uint16_be',
    'fr': 'uint16_be',
    'it': 'uint16_be',
    'es': 'uint16_be',
    'pl': 'uint16_be',
    'zh-cn': 'uint16_be'
  },
  'uint16_le': {
    'en': 'uint16_le',
    'de': 'uint16_le',
    'ru': 'uint16_le',
    'pt': 'uint16_le',
    'nl': 'uint16_le',
    'fr': 'uint16_le',
    'it': 'uint16_le',
    'es': 'uint16_le',
    'pl': 'uint16_le',
    'zh-cn': 'uint16_le'
  },
  'uint32_be': {
    'en': 'uint32_be',
    'de': 'uint32_be',
    'ru': 'uint32_be',
    'pt': 'uint32_be',
    'nl': 'uint32_be',
    'fr': 'uint32_be',
    'it': 'uint32_be',
    'es': 'uint32_be',
    'pl': 'uint32_be',
    'zh-cn': 'uint32_be'
  },
  'uint32_le': {
    'en': 'uint32_le',
    'de': 'uint32_le',
    'ru': 'uint32_le',
    'pt': 'uint32_le',
    'nl': 'uint32_le',
    'fr': 'uint32_le',
    'it': 'uint32_le',
    'es': 'uint32_le',
    'pl': 'uint32_le',
    'zh-cn': 'uint32_le'
  },
  'uint8': {
    'en': 'uint8',
    'de': 'uint8',
    'ru': 'uint8',
    'pt': 'uint8',
    'nl': 'uint8',
    'fr': 'uint8',
    'it': 'uint8',
    'es': 'uint8',
    'pl': 'uint8',
    'zh-cn': 'uint8'
  },
  'value': {
    'en': 'value',
    'de': 'Wert',
    'ru': 'величина́',
    'pt': 'valor',
    'nl': 'waarde',
    'fr': 'valeur',
    'it': 'valore',
    'es': 'valor',
    'pl': 'wartość',
    'zh-cn': '值'
  },
};
